### ISSUE TITLE
Mac OS - VLC autopause with incoming calls not working

### ISSUE THREAD

**Issue by lauperezm** [unifiedremote/Remotes#45] opened 2015-12-14 16:20 UTC
Potential bug: auto-pause with VLC remotes in Mac OS not working (https://unifiedremote.zendesk.com/agent/tickets/4177)

**Comment by pqvst** [comment] 2016-06-29 12:20
Can't reproduce in VLC basic.
Fixed in VLC advanced. Added auto-pause to VLC advanced.

**Closed by pqvst** 2016-06-29 12:20 UTC
Labels: bug
